### ISSUE TITLE
"fatal: not a valid object name: HEAD" on build

### ISSUE THREAD

**Issue by ainola** [poljar/python-olm#9]
Something seems to be wrong in the `install` target when building:

```
writing manifest file 'python_olm_dev.egg-info/SOURCES.txt'
fatal: not a valid object name: HEAD
listing git files failed - pretending there aren't any
Traceback (most recent call last):
  File "/usr/lib/python3.7/tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.7/tarfile.py", line 1095, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/lib/python3.7/tarfile.py", line 1031, in frombuf
    raise EmptyHeaderError("empty header")
tarfile.EmptyHeaderError: empty header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/setuptools_scm/file_finder_git.py", line 49, in _git_ls_files_and_dirs
    return _git_interpret_archive(proc.stdout, toplevel)
  File "/usr/lib/python3.7/site-packages/setuptools_scm/file_finder_git.py", line 31, in _git_interpret_archive
    tf = tarfile.open(fileobj=fd, mode="r|*")
  File "/usr/lib/python3.7/tarfile.py", line 1603, in open
    t = cls(name, filemode, stream, **kwargs)
  File "/usr/lib/python3.7/tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.7/tarfile.py", line 2304, in next
    raise ReadError("empty file")
tarfile.ReadError: empty file
reading manifest file 'python_olm_dev.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'python_olm_dev.egg-info/SOURCES.txt'
Copying python_olm_dev.egg-info to /home/ainola/git/AUR/python-olm/pkg/python-olm/usr/lib/python3.7/site-packages/python_olm_dev-3.0-py3.7.egg-info
running install_scripts

```

Arch Linux x86_64, using a slightly modified version of the PKGBUILD you've got in this repo.

**Comment by poljar** [comment]
This error seems to indicate that the tarball is an empty file:
`tarfile.EmptyHeaderError: empty header`.

The bindings are nowadays on [pypi](https://pypi.org/project/python-olm/), I suggest you to use that to create a PKGBUILD since this repo will be archived soon.

Note that you need the latest release of the Olm C lib for the pypi version, while I can't produce a source tarball of the release the latest master tarball should be fine since there wasn't anything big since the release.

Here is the link to the C lib tarball: https://gitlab.matrix.org/matrix-org/olm/-/archive/master/olm-master.tar.bz2

**Comment by poljar** [comment]
There is an AUR package for python-olm now: https://aur.archlinux.org/packages/python-olm/
